global:
  scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'service_1'
    static_configs:
      - targets: ['service_1:8001']
  - job_name: 'service_2'
    static_configs:
      - targets: ['service_2:8002']
